# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_marks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='section',
            new_name='sec',
        ),
    ]
