# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qriousapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custuser',
            name='is_emer_blue',
        ),
        migrations.RemoveField(
            model_name='custuser',
            name='is_emer_green',
        ),
        migrations.RemoveField(
            model_name='custuser',
            name='is_emer_red',
        ),
        migrations.RemoveField(
            model_name='custuser',
            name='is_emer_yellow',
        ),
    ]
