# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qriousapp', '0002_auto_20180118_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='is_emer_blue',
            new_name='is_emerald',
        ),
        migrations.RemoveField(
            model_name='level',
            name='is_emer_green',
        ),
        migrations.RemoveField(
            model_name='level',
            name='is_emer_red',
        ),
        migrations.RemoveField(
            model_name='level',
            name='is_emer_yellow',
        ),
    ]
