# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-20 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qriousapp', '0003_auto_20180118_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='prob_num',
        ),
        migrations.AddField(
            model_name='problem',
            name='prob_data',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='prob_diff',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='prob_help',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='prob_hint',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
