# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-20 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qriousapp', '0005_auto_20180120_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='prob_diff',
            field=models.IntegerField(default=0),
        ),
    ]
