# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qriousapp', '0006_auto_20180120_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custuser',
            name='forfeited_ques_list',
            field=models.CharField(default=[0], max_length=100),
        ),
        migrations.AlterField(
            model_name='custuser',
            name='success_ques_list',
            field=models.CharField(default=[0], max_length=100),
        ),
    ]
